### ISSUE TITLE
pulumi import SAML Application panic

### ISSUE THREAD

**Issue by ericpardee** [pulumi/pulumi-okta#230]
### What happened?

Attempting to import an Okta SAML Application

### Steps to reproduce

`pulumi import okta:app/saml:Saml sitka-uat 0oa5fakedataHPE1d7`

### Expected Behavior

Import Okta SAML Application as `sitka-uat`

### Actual Behavior

```
Previewing import (sitka/uat)

View Live: https://app.pulumi.com/sitka/customer-identity/uat/previews/acc40b2a-ad27-44dd-9fb7-0aec1e82aa7b

     Type                 Name                   Plan       Info
     pulumi:pulumi:Stack  customer-identity-uat             1 error; 27 messages
 =   └─ okta:app:Saml     sitka-uat              import     1 error

Diagnostics:
  pulumi:pulumi:Stack (customer-identity-uat):
    error: preview failed

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x164c8e8]
    goroutine 29 [running]:
    github.com/okta/terraform-provider-okta/okta.resourceAppSamlRead({0x2127ef0, 0xc0005246c0}, 0xc00068c900, {0x1d3fb80?, 0xc0004e07e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-okta@v0.0.0-20220927205311-8eda5263c6d4/okta/resource_okta_app_saml.go:531 +0xbc8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000191960, {0x2127eb8, 0xc00004c090}, 0xd?, {0x1d3fb80, 0xc0004e07e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:729 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000191960, {0x2127eb8, 0xc00004c090}, 0xc0002d76c0, {0x1d3fb80, 0xc0004e07e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:1020 +0x585
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Refresh({0xc0005d5788?}, {0x1eec447, 0xd}, {0x21289a8?, 0xc00012c340})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfshim/sdk-v2/provider.go:135 +0x154
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc0003178c0, {0x2127f28?, 0xc000a8fe00?}, 0xc0005245a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfbridge/provider.go:951 +0x631
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x2127f28, 0xc000a8fe00}, {0x1e44f20?, 0xc0005245a0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3743 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x2127f28, 0xc000a8fb60}, {0x1e44f20, 0xc0005245a0}, 0xc000a92320, 0xc000378888)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1eb11c0?, 0xc0003178c0}, {0x2127f28, 0xc000a8fb60}, 0xc00024c150, 0xc0003eb100)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3745 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027c5a0, {0x212e060, 0xc0004a69c0}, 0xc0004de120, 0xc0004d4870, 0x2a50718, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
    google.golang.org/grpc.(*Server).handleStream(0xc00027c5a0, {0x212e060, 0xc0004a69c0}, 0xc0004de120, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

  okta:app:Saml (sitka-uat):
    error: Preview failed: error reading from server: EOF
```

### Output of `pulumi about`

```
$ pulumi about                                                                                                                                                             255 ↵
CLI
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
okta    3.16.0
python  unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in python: executable='/Users/ericpardee/sitka/sitka-iac/okta/customer-identity/venv/bin/python3' version='3.10.2
'

Current Stack: sitka/uat

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:uat::customer-identity::pulumi:pulumi:Stack::customer-identity-uat
pulumi:providers:okta      urn:pulumi:uat::customer-identity::pulumi:providers:okta::default_3_11_0
okta:policy/signon:Signon  urn:pulumi:uat::customer-identity::okta:policy/signon:Signon::example


Found no pending operations associated with sitka/uat

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ericpardee
User           ericpardee
Organizations  ericpardee, sitka

Dependencies:
NAME         VERSION
pip          22.2.2
pulumi-okta  3.16.0
setuptools   58.1.0

Pulumi locates its logs in /var/folders/nv/tlr7w_gd6qs6ydk74klkl1z80000gp/T/ by default
```

### Additional context

`OKTA_ORG_NAME`, `OKTA_BASE_URL`, and `OKTA_API_TOKEN` are set and working with other okta provider resources.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Looks like this was fixed upstream as of March 10, should be in our latest release.

**Comment by ericpardee** [comment]
**This is still broken**

```
$ pulumi import okta:app/saml:Saml sitka-uat 0oa5fakedataHPE1d7
Previewing import (sitka/uat)

View in Browser (Ctrl+O): https://app.pulumi.com/sitka/customer-identity/uat/previews/390d0d6f-5330-45bc-8114-d0ce147eb771

     Type                 Name                   Plan       Info
     pulumi:pulumi:Stack  customer-identity-uat             1 error; 27 messages
 =   └─ okta:app:Saml     sitka-uat              import     1 error


Diagnostics:
  pulumi:pulumi:Stack (customer-identity-uat):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x164c8e8]
    goroutine 61 [running]:
    github.com/okta/terraform-provider-okta/okta.resourceAppSamlRead({0x2127ef0, 0xc000051800}, 0xc0002d6e00, {0x1d3fb80?, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-okta@v0.0.0-20220927205311-8eda5263c6d4/okta/resource_okta_app_saml.go:531 +0xbc8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00018d960, {0x2127eb8, 0xc00004c0a0}, 0xd?, {0x1d3fb80, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:729 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00018d960, {0x2127eb8, 0xc00004c0a0}, 0xc00022d5f0, {0x1d3fb80, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:1020 +0x585
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Refresh({0xc000a0b788?}, {0x1eec447, 0xd}, {0x21289a8?, 0xc0000f98b0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfshim/sdk-v2/provider.go:135 +0x154
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc0002ea000, {0x2127f28?, 0xc000529920?}, 0xc0000516e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfbridge/provider.go:951 +0x631
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x2127f28, 0xc000529920}, {0x1e44f20?, 0xc0000516e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3743 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x2127f28, 0xc000529680}, {0x1e44f20, 0xc0000516e0}, 0xc0004469a0, 0xc0002a3830)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1eb11c0?, 0xc0002ea000}, {0x2127f28, 0xc000529680}, 0xc000a2e2a0, 0xc0002e0000)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3745 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e6000, {0x212e060, 0xc000702820}, 0xc00081c000, 0xc0002d82a0, 0x2a50718, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
    google.golang.org/grpc.(*Server).handleStream(0xc0002e6000, {0x212e060, 0xc000702820}, 0xc00081c000, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

    error: preview failed

  okta:app:Saml (sitka-uat):
    error: Preview failed: error reading from server: EOF
```

**Pulumi about:**
```
$ pulumi about                                                                                                                                                                                                                          255 ↵
CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
okta    3.16.0
python  unknown

Host
OS       darwin
Version  13.3
Arch     x86_64

This project is written in python: executable='/Users/ericpardee/.asdf/shims/python3' version='3.11.0
'

Current Stack: sitka/customer-identity/uat

TYPE                    URN
pulumi:pulumi:Stack     urn:pulumi:uat::customer-identity::pulumi:pulumi:Stack::customer-identity-uat
pulumi:providers:okta   urn:pulumi:uat::customer-identity::pulumi:providers:okta::default_3_16_0
okta:group/group:Group  urn:pulumi:uat::customer-identity::okta:group/group:Group::Sitka UAT for Internal SSO Testing

Found no pending operations associated with sitka/uat

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ericpardee
User           ericpardee
Organizations  ericpardee, sitka

Dependencies:
NAME         VERSION
pip          22.2.2
pulumi-okta  3.16.0
setuptools   58.1.0

Pulumi locates its logs in /var/folders/nv/tlr7w_gd6qs6ydk74klkl1z80000gp/T/ by default
```

**Comment by ericpardee** [comment]
**This is still broken**
```
$ pulumi import okta:app/saml:Saml sitka-uat 0oa5fakedataHPE1d7
Previewing import (sitka/uat)

View in Browser (Ctrl+O): https://app.pulumi.com/sitka/customer-identity/uat/previews/390d0d6f-5330-45bc-8114-d0ce147eb771

     Type                 Name                   Plan       Info
     pulumi:pulumi:Stack  customer-identity-uat             1 error; 27 messages
 =   └─ okta:app:Saml     sitka-uat              import     1 error


Diagnostics:
  pulumi:pulumi:Stack (customer-identity-uat):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x164c8e8]
    goroutine 61 [running]:
    github.com/okta/terraform-provider-okta/okta.resourceAppSamlRead({0x2127ef0, 0xc000051800}, 0xc0002d6e00, {0x1d3fb80?, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-okta@v0.0.0-20220927205311-8eda5263c6d4/okta/resource_okta_app_saml.go:531 +0xbc8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00018d960, {0x2127eb8, 0xc00004c0a0}, 0xd?, {0x1d3fb80, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:729 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00018d960, {0x2127eb8, 0xc00004c0a0}, 0xc00022d5f0, {0x1d3fb80, 0xc000020480})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:1020 +0x585
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Refresh({0xc000a0b788?}, {0x1eec447, 0xd}, {0x21289a8?, 0xc0000f98b0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfshim/sdk-v2/provider.go:135 +0x154
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc0002ea000, {0x2127f28?, 0xc000529920?}, 0xc0000516e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.27.0/pkg/tfbridge/provider.go:951 +0x631
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x2127f28, 0xc000529920}, {0x1e44f20?, 0xc0000516e0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3743 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x2127f28, 0xc000529680}, {0x1e44f20, 0xc0000516e0}, 0xc0004469a0, 0xc0002a3830)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1eb11c0?, 0xc0002ea000}, {0x2127f28, 0xc000529680}, 0xc000a2e2a0, 0xc0002e0000)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.37.2/proto/go/provider.pb.go:3745 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e6000, {0x212e060, 0xc000702820}, 0xc00081c000, 0xc0002d82a0, 0x2a50718, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
    google.golang.org/grpc.(*Server).handleStream(0xc0002e6000, {0x212e060, 0xc000702820}, 0xc00081c000, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

    error: preview failed

  okta:app:Saml (sitka-uat):
    error: Preview failed: error reading from server: EOF
```

**Pulumi about**
```
$ pulumi about                                                                                                                                                                                                                          255 ↵
CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
okta    3.16.0
python  unknown

Host
OS       darwin
Version  13.3
Arch     x86_64

This project is written in python: executable='/Users/ericpardee/.asdf/shims/python3' version='3.11.0
'

Current Stack: sitka/customer-identity/uat

TYPE                    URN
pulumi:pulumi:Stack     urn:pulumi:uat::customer-identity::pulumi:pulumi:Stack::customer-identity-uat
pulumi:providers:okta   urn:pulumi:uat::customer-identity::pulumi:providers:okta::default_3_16_0
okta:group/group:Group  urn:pulumi:uat::customer-identity::okta:group/group:Group::Sitka UAT for Internal SSO Testing

Found no pending operations associated with sitka/uat

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ericpardee
User           ericpardee
Organizations  ericpardee, sitka

Dependencies:
NAME         VERSION
pip          22.2.2
pulumi-okta  3.16.0
setuptools   58.1.0

Pulumi locates its logs in /var/folders/nv/tlr7w_gd6qs6ydk74klkl1z80000gp/T/ by default
```
